workflows:
  my-workflow:
    max_build_duration: 120
    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize && security import ~/clone/Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P 'password'
      - name: Build
        script: cd ~/clone/ && make all
    artifacts:
      - Tools/*.ipa
